import { AgentDefinition, AgentStatus } from "../types/agents";
import { OutputModelName } from "../types/outputs";

export const agents: AgentDefinition[] = [
  {
    id: "business_strategist",
    name: "Business Strategist",
    description: "Crafts high-level business strategy and priorities.",
    responsibilities: ["Define objectives", "Prioritize initiatives", "Set KPIs"],
    inputSchema: { type: "object", properties: {}, required: [] },
    outputSchema: { type: "object", properties: {}, required: [] },
    // expected output model
    outputModel: "BusinessPlan" as OutputModelName,
    status: AgentStatus.Idle,
    priority: 1,
  },
  {
    id: "market_research",
    name: "Market Research Agent",
    description: "Collects market data, customer segments and trends.",
    responsibilities: ["Estimate market size", "Identify trends", "Segment customers"],
    inputSchema: { type: "object", properties: {}, required: [] },
    outputSchema: { type: "object", properties: {}, required: [] },
    status: AgentStatus.Idle,
    outputModel: "MarketResearch" as OutputModelName,
    priority: 2,
  },
  {
    id: "financial_analyst",
    name: "Financial Analyst",
    description: "Builds financial projections, budgets and models.",
    responsibilities: ["Create projections", "Estimate costs", "Model scenarios"],
    inputSchema: { type: "object", properties: {}, required: [] },
    outputSchema: { type: "object", properties: {}, required: [] },
    status: AgentStatus.Idle,
    outputModel: "FinancialReport" as OutputModelName,
    priority: 3,
  },
  {
    id: "brand_strategist",
    name: "Brand Strategist",
    description: "Defines brand positioning, voice and messaging.",
    responsibilities: ["Positioning", "Messaging", "Visual direction"],
    inputSchema: { type: "object", properties: {}, required: [] },
    outputSchema: { type: "object", properties: {}, required: [] },
    status: AgentStatus.Idle,
    outputModel: "BrandStrategy" as OutputModelName,
    priority: 4,
  },
  {
    id: "naming_expert",
    name: "Naming Expert",
    description: "Generates and filters name candidates.",
    responsibilities: ["Generate names", "Filter trademarks", "Assess domain availability"],
    inputSchema: { type: "object", properties: {}, required: [] },
    outputSchema: { type: "object", properties: {}, required: [] },
    status: AgentStatus.Idle,
    outputModel: "ProjectSummary" as OutputModelName,
    priority: 5,
  },
  {
    id: "logo_director",
    name: "Logo Director",
    description: "Produces logo concepts and variations.",
    responsibilities: ["Sketch concepts", "Provide variations", "Export assets"],
    inputSchema: { type: "object", properties: {}, required: [] },
    outputSchema: { type: "object", properties: {}, required: [] },
    status: AgentStatus.Idle,
    outputModel: "LogoConcept" as OutputModelName,
    priority: 6,
  },
  {
    id: "visual_identity",
    name: "Visual Identity Expert",
    description: "Defines color palettes, typography and guidelines.",
    responsibilities: ["Color palettes", "Typography", "Usage guidelines"],
    inputSchema: { type: "object", properties: {}, required: [] },
    outputSchema: { type: "object", properties: {}, required: [] },
    status: AgentStatus.Idle,
    outputModel: "VisualIdentity" as OutputModelName,
    priority: 7,
  },
  {
    id: "website_architect",
    name: "Website Architect",
    description: "Designs website structure and content map.",
    responsibilities: ["Sitemap", "Page purpose", "Content outline"],
    inputSchema: { type: "object", properties: {}, required: [] },
    outputSchema: { type: "object", properties: {}, required: [] },
    status: AgentStatus.Idle,
    outputModel: "WebsiteStructure" as OutputModelName,
    priority: 8,
  },
  {
    id: "marketing_strategist",
    name: "Marketing Strategist",
    description: "Builds go-to-market and channel strategies.",
    responsibilities: ["Channel plans", "Campaigns", "KPIs"],
    inputSchema: { type: "object", properties: {}, required: [] },
    outputSchema: { type: "object", properties: {}, required: [] },
    status: AgentStatus.Idle,
    outputModel: "MarketingPlan" as OutputModelName,
    priority: 9,
  },
  {
    id: "operations_consultant",
    name: "Operations Consultant",
    description: "Advises on processes, team structure and ops." ,
    responsibilities: ["Team structure", "Processes", "Operations checklist"],
    inputSchema: { type: "object", properties: {}, required: [] },
    outputSchema: { type: "object", properties: {}, required: [] },
    status: AgentStatus.Idle,
    outputModel: "OperationsPlan" as OutputModelName,
    priority: 10,
  },
  {
    id: "pitch_deck_expert",
    name: "Pitch Deck Expert",
    description: "Creates investor-ready pitch deck slides.",
    responsibilities: ["Slide outlines", "Narrative flow", "Design notes"],
    inputSchema: { type: "object", properties: {}, required: [] },
    outputSchema: { type: "object", properties: {}, required: [] },
    status: AgentStatus.Idle,
    outputModel: "PitchDeck" as OutputModelName,
    priority: 11,
  },
  {
    id: "growth_advisor",
    name: "Growth Advisor",
    description: "Suggests experiments and growth channels.",
    responsibilities: ["Experiment ideas", "Metrics", "Prioritization"],
    inputSchema: { type: "object", properties: {}, required: [] },
    outputSchema: { type: "object", properties: {}, required: [] },
    status: AgentStatus.Idle,
    outputModel: "GrowthRoadmap" as OutputModelName,
    priority: 12,
  },
];

export default agents;
