import type { BusinessVertical, RevenueComponent, RevenueModel, SalesChannel, VerticalTemplate } from "./types";

type CompatibilityRule = {
  allowedPrimaryRevenueModels: RevenueModel[];
  allowedSecondaryRevenueModels: RevenueModel[];
  allowedSalesChannels: SalesChannel[];
  allowedRevenueComponents: RevenueComponent[];
};

const compatibilityRules: Record<BusinessVertical, CompatibilityRule> = {
  restaurant_food_service: {
    allowedPrimaryRevenueModels: ["transaction_sales", "service_fees", "mixed"],
    allowedSecondaryRevenueModels: ["service_fees", "subscription"],
    allowedSalesChannels: ["dine_in", "takeaway", "drive_thru", "delivery"],
    allowedRevenueComponents: ["transaction_sales", "delivery_fee", "add_on_products"],
  },
  saas_software: {
    allowedPrimaryRevenueModels: ["subscription", "usage_based", "mixed"],
    allowedSecondaryRevenueModels: ["subscription", "usage_based", "service_fees", "advertising"],
    allowedSalesChannels: ["website", "direct_sales", "partner_sales", "mobile_app"],
    allowedRevenueComponents: ["monthly_subscription", "annual_subscription", "usage_fee", "advertising", "licensing"],
  },
  marketplace: {
    allowedPrimaryRevenueModels: ["marketplace_commission", "mixed"],
    allowedSecondaryRevenueModels: ["subscription", "service_fees", "advertising", "transaction_sales"],
    allowedSalesChannels: ["website", "mobile_app", "partner_sales"],
    allowedRevenueComponents: ["transaction_commission", "listing_fee", "advertising"],
  },
  professional_services: {
    allowedPrimaryRevenueModels: ["service_fees", "mixed"],
    allowedSecondaryRevenueModels: ["subscription", "usage_based", "service_fees"],
    allowedSalesChannels: ["direct_sales", "website", "partner_sales", "project_fees", "retainers", "advisory"],
    allowedRevenueComponents: ["service_fee", "retainer_fee", "licensing"],
  },
  ecommerce_retail: {
    allowedPrimaryRevenueModels: ["transaction_sales", "mixed"],
    allowedSecondaryRevenueModels: ["subscription", "service_fees", "advertising"],
    allowedSalesChannels: ["online_store", "website", "marketplaces", "social_commerce", "mobile_app"],
    allowedRevenueComponents: ["transaction_sales", "delivery_fee", "advertising", "add_on_products"],
  },
  subscription_service: {
    allowedPrimaryRevenueModels: ["subscription", "mixed"],
    allowedSecondaryRevenueModels: ["usage_based", "service_fees", "transaction_sales"],
    allowedSalesChannels: ["website", "mobile_app", "delivery", "direct_sales"],
    allowedRevenueComponents: ["weekly_subscription", "monthly_subscription", "annual_subscription", "add_on_products"],
  },
  physical_retail: {
    allowedPrimaryRevenueModels: ["transaction_sales", "mixed"],
    allowedSecondaryRevenueModels: ["subscription", "service_fees"],
    allowedSalesChannels: ["in_store_sales", "point_of_sale", "takeaway", "delivery"],
    allowedRevenueComponents: ["transaction_sales", "add_on_products"],
  },
  manufacturing: {
    allowedPrimaryRevenueModels: ["transaction_sales", "licensing", "mixed"],
    allowedSecondaryRevenueModels: ["licensing", "service_fees"],
    allowedSalesChannels: ["direct_sales", "partner_sales", "wholesale_orders", "b2b_contracts"],
    allowedRevenueComponents: ["transaction_sales", "licensing"],
  },
  real_estate: {
    allowedPrimaryRevenueModels: ["rental", "service_fees", "mixed"],
    allowedSecondaryRevenueModels: ["transaction_sales", "marketplace_commission"],
    allowedSalesChannels: ["direct_sales", "website", "partner_sales", "broker_commissions", "lease_fees"],
    allowedRevenueComponents: ["rental_income", "service_fee", "transaction_commission"],
  },
  logistics_delivery: {
    allowedPrimaryRevenueModels: ["service_fees", "transaction_sales", "mixed"],
    allowedSecondaryRevenueModels: ["subscription", "usage_based", "service_fees"],
    allowedSalesChannels: ["delivery", "website", "mobile_app", "partner_sales", "service_contracts"],
    allowedRevenueComponents: ["service_fee", "delivery_fee", "transaction_sales"],
  },
  education_training: {
    allowedPrimaryRevenueModels: ["service_fees", "subscription", "mixed"],
    allowedSecondaryRevenueModels: ["usage_based", "transaction_sales"],
    allowedSalesChannels: ["website", "mobile_app", "partner_sales", "direct_sales", "course_fees"],
    allowedRevenueComponents: ["service_fee", "monthly_subscription", "annual_subscription", "usage_fee"],
  },
  healthcare_wellness: {
    allowedPrimaryRevenueModels: ["service_fees", "subscription", "mixed"],
    allowedSecondaryRevenueModels: ["usage_based", "transaction_sales"],
    allowedSalesChannels: ["direct_sales", "website", "partner_sales", "consultation_fees", "package_plans"],
    allowedRevenueComponents: ["service_fee", "monthly_subscription", "annual_subscription"],
  },
  generic_other: {
    allowedPrimaryRevenueModels: ["unknown", "transaction_sales", "service_fees", "subscription", "mixed"],
    allowedSecondaryRevenueModels: ["transaction_sales", "service_fees", "subscription", "usage_based", "advertising", "licensing"],
    allowedSalesChannels: ["direct_sales", "website", "partner_sales", "mobile_app"],
    allowedRevenueComponents: ["unknown", "transaction_sales", "service_fee", "monthly_subscription", "advertising"],
  },
  unknown: {
    allowedPrimaryRevenueModels: ["unknown"],
    allowedSecondaryRevenueModels: [],
    allowedSalesChannels: ["unknown"],
    allowedRevenueComponents: ["unknown"],
  },
};

const templates: Record<BusinessVertical, VerticalTemplate> = {
  restaurant_food_service: {
    verticalId: "restaurant_food_service",
    version: "1.0.0",
    applicableRevenueModels: ["transaction_sales", "service_fees", "mixed"],
    revenueDrivers: ["average_order_value", "daily_transactions", "operating_days_per_month", "channel_mix", "beverage_attachment_rate"],
    costCategories: ["rent", "payroll", "food_cost", "packaging", "delivery_commissions", "utilities", "marketing"],
    financialKPIs: ["gross_margin", "contribution_margin", "food_cost_percentage", "break_even_daily_orders"],
    marketResearchTaxonomy: ["local_eating_habits", "delivery_behavior", "pricing_sensitivity", "location_dynamics"],
    competitorCategories: ["quick_service_restaurants", "healthy_food_chains", "independent_breakfast_shops"],
    requiredInputs: ["country", "city", "targetAudience", "launchTimeline"],
    optionalInputs: ["budgetRange", "customerAgeRange"],
    allowedOutputPatterns: ["currency_labeled_amounts", "assumption_labels", "scenario_forecasts"],
    forbiddenOutputPatterns: ["saas_pricing_tiers", "unlabeled_currency", "placeholder_competitors"],
    defaultAssumptions: ["No currency conversion is applied.", "External evidence may require validation if no verified source is available."],
    confidenceRules: ["Lower confidence when location data is missing.", "Reject unsupported precise market-size claims."],
  },
  saas_software: {
    verticalId: "saas_software",
    version: "1.0.0",
    applicableRevenueModels: ["subscription", "usage_based", "mixed"],
    revenueDrivers: ["mrr", "arr", "arpa", "churn", "retention", "new_accounts"],
    costCategories: ["engineering_payroll", "cloud_infrastructure", "customer_support", "sales_marketing"],
    financialKPIs: ["gross_margin", "burn_rate", "runway", "ltv_cac_ratio"],
    marketResearchTaxonomy: ["category_adoption", "buyer_segments", "switching_costs", "software_spend"],
    competitorCategories: ["direct_saas_competitors", "adjacent_tools"],
    requiredInputs: ["targetAudience", "businessStage"],
    optionalInputs: ["launchTimeline", "budgetRange"],
    allowedOutputPatterns: ["subscription_or_usage_pricing", "kpi_definitions"],
    forbiddenOutputPatterns: ["restaurant_operational_drivers"],
    defaultAssumptions: ["Retention assumptions are model-based unless verified."],
    confidenceRules: ["Reduce confidence when pricing inputs are missing."],
  },
  ecommerce_retail: {
    verticalId: "ecommerce_retail",
    version: "1.0.0",
    applicableRevenueModels: ["transaction_sales", "mixed"],
    revenueDrivers: ["average_order_value", "conversion_rate", "traffic", "repeat_purchase_rate"],
    costCategories: ["inventory", "fulfillment", "shipping", "returns", "ad_spend", "payment_fees"],
    financialKPIs: ["contribution_margin", "inventory_turnover", "return_rate"],
    marketResearchTaxonomy: ["online_shopping_behavior", "category_demand", "price_sensitivity"],
    competitorCategories: ["online_stores", "marketplace_sellers"],
    requiredInputs: ["country", "targetAudience"],
    optionalInputs: ["budgetRange", "launchTimeline"],
    allowedOutputPatterns: ["transaction_sales_model", "currency_labeled_amounts"],
    forbiddenOutputPatterns: ["saas_only_metrics_without_context"],
    defaultAssumptions: ["Demand assumptions are conservative without verified datasets."],
    confidenceRules: ["Lower confidence if product category is broad."],
  },
  professional_services: {
    verticalId: "professional_services",
    version: "1.0.0",
    applicableRevenueModels: ["service_fees", "mixed"],
    revenueDrivers: ["billable_rate", "utilization", "project_volume", "retainer_share"],
    costCategories: ["payroll", "contractors", "software", "business_development"],
    financialKPIs: ["gross_margin", "utilization_rate", "collections_cycle"],
    marketResearchTaxonomy: ["service_demand", "buyer_profiles", "procurement_behavior"],
    competitorCategories: ["agencies", "independent_consultants"],
    requiredInputs: ["targetAudience", "businessStage"],
    optionalInputs: ["budgetRange", "city"],
    allowedOutputPatterns: ["service_fee_revenue_model", "assumption_disclosure"],
    forbiddenOutputPatterns: ["saas_tier_defaults", "restaurant_channel_mix"],
    defaultAssumptions: ["Utilization estimates are assumptions unless historical utilization is provided."],
    confidenceRules: ["Lower confidence if billable-rate anchor is missing."],
  },
  marketplace: {
    verticalId: "marketplace",
    version: "1.0.0",
    applicableRevenueModels: ["marketplace_commission", "mixed"],
    revenueDrivers: ["gmv", "take_rate", "buyer_activity", "seller_activity", "transaction_frequency"],
    costCategories: ["payment_fees", "trust_safety", "incentives", "acquisition_costs"],
    financialKPIs: ["net_revenue", "liquidity", "take_rate_realization"],
    marketResearchTaxonomy: ["two_sided_supply_demand", "category_penetration", "switching_behavior"],
    competitorCategories: ["horizontal_marketplaces", "vertical_marketplaces"],
    requiredInputs: ["country", "targetAudience"],
    optionalInputs: ["city", "launchTimeline"],
    allowedOutputPatterns: ["commission_model", "liquidity_metrics"],
    forbiddenOutputPatterns: ["saas_plan_labels_without_context"],
    defaultAssumptions: ["Liquidity ramp assumptions are model-based."],
    confidenceRules: ["Lower confidence with incomplete buyer/seller assumptions."],
  },
  subscription_service: {
    verticalId: "subscription_service",
    version: "1.0.0",
    applicableRevenueModels: ["subscription", "mixed"],
    revenueDrivers: ["subscriber_count", "average_subscription_fee", "churn"],
    costCategories: ["service_delivery", "operations", "marketing"],
    financialKPIs: ["mrr", "churn", "contribution_margin"],
    marketResearchTaxonomy: ["subscription_behavior", "retention_patterns"],
    competitorCategories: ["subscription_brands"],
    requiredInputs: ["targetAudience"],
    optionalInputs: ["launchTimeline"],
    allowedOutputPatterns: ["subscription_metrics", "currency_labeled_amounts"],
    forbiddenOutputPatterns: ["placeholder_competitors"],
    defaultAssumptions: ["Retention estimates are assumptions without historical data."],
    confidenceRules: ["Lower confidence when churn assumptions are missing."],
  },
  physical_retail: {
    verticalId: "physical_retail",
    version: "1.0.0",
    applicableRevenueModels: ["transaction_sales"],
    revenueDrivers: ["store_traffic", "conversion_rate", "average_ticket_size"],
    costCategories: ["rent", "inventory", "payroll", "utilities"],
    financialKPIs: ["gross_margin", "sales_per_square_meter"],
    marketResearchTaxonomy: ["footfall", "local_competition", "pricing_sensitivity"],
    competitorCategories: ["local_retailers"],
    requiredInputs: ["country", "city"],
    optionalInputs: ["budgetRange"],
    allowedOutputPatterns: ["transaction_sales_model"],
    forbiddenOutputPatterns: ["saas_pricing_tiers"],
    defaultAssumptions: ["Footfall assumptions are estimates without site analytics."],
    confidenceRules: ["Lower confidence if location precision is low."],
  },
  manufacturing: {
    verticalId: "manufacturing",
    version: "1.0.0",
    applicableRevenueModels: ["transaction_sales", "licensing"],
    revenueDrivers: ["unit_output", "unit_price", "capacity_utilization"],
    costCategories: ["materials", "labor", "maintenance", "energy"],
    financialKPIs: ["gross_margin", "capacity_utilization"],
    marketResearchTaxonomy: ["supplier_risk", "demand_cycles"],
    competitorCategories: ["manufacturers", "imported_alternatives"],
    requiredInputs: ["country"],
    optionalInputs: ["city"],
    allowedOutputPatterns: ["costed_unit_economics"],
    forbiddenOutputPatterns: ["saas_only_kpis"],
    defaultAssumptions: ["Material pricing volatility is assumed."],
    confidenceRules: ["Lower confidence when BOM data is missing."],
  },
  real_estate: {
    verticalId: "real_estate",
    version: "1.0.0",
    applicableRevenueModels: ["rental", "service_fees", "mixed"],
    revenueDrivers: ["occupancy", "rent_per_unit", "transaction_fees"],
    costCategories: ["property_maintenance", "staffing", "marketing"],
    financialKPIs: ["occupancy_rate", "yield"],
    marketResearchTaxonomy: ["location_demand", "inventory_supply"],
    competitorCategories: ["brokers", "property_platforms"],
    requiredInputs: ["country", "city"],
    optionalInputs: ["launchTimeline"],
    allowedOutputPatterns: ["rental_or_fee_model"],
    forbiddenOutputPatterns: ["saas_plan_defaults"],
    defaultAssumptions: ["Occupancy assumptions are model-based."],
    confidenceRules: ["Lower confidence when unit inventory is unknown."],
  },
  logistics_delivery: {
    verticalId: "logistics_delivery",
    version: "1.0.0",
    applicableRevenueModels: ["service_fees", "transaction_sales", "mixed"],
    revenueDrivers: ["deliveries_per_day", "average_fee", "fleet_utilization"],
    costCategories: ["fuel", "drivers", "maintenance", "routing_software"],
    financialKPIs: ["delivery_margin", "on_time_rate"],
    marketResearchTaxonomy: ["delivery_demand", "service_radius"],
    competitorCategories: ["delivery_networks"],
    requiredInputs: ["country", "city"],
    optionalInputs: ["budgetRange"],
    allowedOutputPatterns: ["service_fee_model"],
    forbiddenOutputPatterns: ["saas_tier_defaults"],
    defaultAssumptions: ["Demand per zone is estimated unless telemetry exists."],
    confidenceRules: ["Lower confidence without route-density assumptions."],
  },
  education_training: {
    verticalId: "education_training",
    version: "1.0.0",
    applicableRevenueModels: ["service_fees", "subscription", "mixed"],
    revenueDrivers: ["student_enrollment", "course_price", "completion_rate"],
    costCategories: ["instructor_costs", "platform_costs", "content_production"],
    financialKPIs: ["completion_rate", "cost_per_student"],
    marketResearchTaxonomy: ["learner_segments", "skills_demand"],
    competitorCategories: ["academies", "online_platforms"],
    requiredInputs: ["targetAudience"],
    optionalInputs: ["country", "city"],
    allowedOutputPatterns: ["fee_or_subscription_model"],
    forbiddenOutputPatterns: ["placeholder_competitors"],
    defaultAssumptions: ["Enrollment conversion assumptions are model-based."],
    confidenceRules: ["Lower confidence without channel strategy."],
  },
  healthcare_wellness: {
    verticalId: "healthcare_wellness",
    version: "1.0.0",
    applicableRevenueModels: ["service_fees", "subscription", "mixed"],
    revenueDrivers: ["appointments", "package_uptake", "repeat_rate"],
    costCategories: ["clinical_staff", "facility", "supplies", "compliance"],
    financialKPIs: ["capacity_utilization", "retention_rate"],
    marketResearchTaxonomy: ["patient_demand", "care_preferences"],
    competitorCategories: ["clinics", "wellness_centers"],
    requiredInputs: ["country", "city"],
    optionalInputs: ["targetAudience"],
    allowedOutputPatterns: ["service_fee_model", "confidence_disclosure"],
    forbiddenOutputPatterns: ["unverified_medical_claims"],
    defaultAssumptions: ["Regulatory constraints require external confirmation."],
    confidenceRules: ["Lower confidence when compliance details are missing."],
  },
  generic_other: {
    verticalId: "generic_other",
    version: "1.0.0",
    applicableRevenueModels: ["unknown", "transaction_sales", "service_fees", "mixed"],
    revenueDrivers: ["demand", "pricing", "conversion"],
    costCategories: ["operations", "people", "marketing"],
    financialKPIs: ["cashflow", "break_even"],
    marketResearchTaxonomy: ["demand_hypotheses", "customer_validation_plan"],
    competitorCategories: ["category_alternatives"],
    requiredInputs: ["businessDescription", "targetAudience"],
    optionalInputs: ["country", "city", "budgetRange"],
    allowedOutputPatterns: ["assumption_labels", "requires_validation_flags"],
    forbiddenOutputPatterns: ["silent_saas_defaults", "placeholder_competitors"],
    defaultAssumptions: ["Use conservative baseline assumptions when uncertain."],
    confidenceRules: ["Request confirmation on low-confidence vertical guesses."],
  },
  unknown: {
    verticalId: "unknown",
    version: "1.0.0",
    applicableRevenueModels: ["unknown"],
    revenueDrivers: ["unresolved"],
    costCategories: ["unresolved"],
    financialKPIs: ["unresolved"],
    marketResearchTaxonomy: ["requires_user_confirmation"],
    competitorCategories: ["requires_user_confirmation"],
    requiredInputs: ["industry", "businessDescription"],
    optionalInputs: [],
    allowedOutputPatterns: ["requires_user_input"],
    forbiddenOutputPatterns: ["silent_saas_defaults"],
    defaultAssumptions: ["Do not fabricate precision when vertical is unknown."],
    confidenceRules: ["Pause for confirmation on unresolved ambiguity."],
  },
};

export function getVerticalTemplate(vertical: BusinessVertical): VerticalTemplate {
  const base = templates[vertical] ?? templates.generic_other;
  const compatibility = compatibilityRules[base.verticalId] ?? compatibilityRules.generic_other;
  return {
    ...base,
    applicableRevenueModels: compatibility.allowedPrimaryRevenueModels,
    allowedSecondaryRevenueModels: compatibility.allowedSecondaryRevenueModels,
    allowedSalesChannels: compatibility.allowedSalesChannels,
    allowedRevenueComponents: compatibility.allowedRevenueComponents,
  };
}
